<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_08_AutoCrossCut" Id="{73f4070d-b53d-44b0-b7c0-d862c4fca4a8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_08_AutoCrossCut
VAR
	iStep: INT;
	TON_DownDelay: TON;
	ctu_DoublePass: CTU;
	bDoublePassCountUp: BOOL;
	TON_bAutoUp: TON;
	bTON_AutoUp: BOOL;
	R_TRIG_0: R_TRIG;
	TON_AutoCrossCutError: TON;
	SR_DoublePass: SR;
	bDoublePassQ: BOOL;
	FB_Blinker_AutoCrossCut: fb_Blinker;
	TON_AutoCrossCutWatchdog: TON;
	SR_watchdog: SR;
	R_TRIG_1: R_TRIG;
	R_TRIG_2: R_TRIG;
	R_TRIG_3: R_TRIG;
	R_TRIG_4: R_TRIG;
	R_TRIG_5: R_TRIG;
	bWatchdogReset: BOOL;
	R_TRIG_6: R_TRIG;
	R_TRIG_7: R_TRIG;
	SR_WatchdogTriggered: SR;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	IF		NOT bSafetyOK OR IN_FaultReset OR NOT OUT_bSawON OR bAnyServoError OR bMachineHoming OR bCrossCutPosition
	THEN	iStep	:=	0 ;
			bWatchdogReset := TRUE ;
	END_IF

(* Automatic cycle watchdog timer *)	
//	TON_AutoCrossCutWatchdog(IN:= , PT:= T#3M, Q=> , ET=> );
	
(* Time delay 0.5 sec after saw blade reached the bottom limit *)	
	TON_DownDelay(IN:= , PT:= T#0.5S, Q=> , ET=> );
	IF		iStep <> 30 THEN
			TON_DownDelay.IN	:= FALSE ;
	END_IF
(* Double Pass counter BOOL *)
	IF		ctu_DoublePass.CV	=	1
	THEN	bDoublePassCountUp		:=	TRUE;
	ELSE	bDoublePassCountUp		:=	FALSE;
	END_IF

CASE iStep OF 
	0:		//	Step 0	:	Init step
				bAutoCrossCut	:= FALSE ;
				bAutoUp			:= FALSE ;
				bAutoDown		:= FALSE ;
				bAutoCut		:= FALSE ;
				bAutoReturn		:= FALSE ;
				bTON_AutoUp		:= FALSE ;
				bWatchdogReset	:= TRUE  ;
				
		IF
				bSafetyOK
				AND bTurret045Range
				AND OUT_bSawON
				AND (bAutoCrossCutEnable AND IN_bAutoCycleStart AND NOT bRemote)
				AND NOT bMachineHoming
				AND NOT bCrossCutPosition
				AND bCarriageCentreRef
		THEN
				bAutoCrossCut := TRUE	;
				bWatchdogReset := TRUE  ;
				iStep	:=		20		;
		ELSE
				bAutoCrossCut := FALSE	;
				bWatchdogReset := FALSE ;
				iStep	:=		0		;
		END_IF

	20:		// Step 20	:	Saw RETURN movement
		IF 
				bAutoCrossCut
				AND bSafetyOK
				AND NOT bCrossCutRightLimit
			
		THEN	bAutoReturn	:=	TRUE	;
				bWatchdogReset := FALSE ;
		
		ELSE
				bAutoReturn	:=	FALSE	;
				bWatchdogReset := TRUE  ;
				iStep		:=	30		;
		END_IF
	
		IF 		NOT bSafetyOK
		THEN 	
				bAutoReturn	:=	FALSE	;
				bWatchdogReset := TRUE  ;
				iStep		:=	0		;
		END_IF
		
	30:		// Step 30	:	Saw DOWN movement
	ctu_DoublePass.CV;
		IF
				bAutoCrossCut
				AND bSafetyOK
				AND ((bAutoCrossCutDoublePass AND NOT bDoublePassReference AND bDoublePassCountUp) 
					OR ( NOT SR_DownLimit.Q1 AND (bDoublePassQ OR NOT bDoublePassCountUp)))
		THEN	
				bAutoDown	:=	TRUE	;
				bWatchdogReset := FALSE ;
		ELSE
				bAutoDown	:=	FALSE	;
				TON_DownDelay.IN := TRUE ;
					IF TON_DownDelay.Q THEN
						bWatchdogReset := TRUE ;
						iStep	:=	40		;
					END_IF
		END_IF
		
		IF 		NOT bSafetyOK
		THEN 	
				bAutoDown	:=	FALSE	;
				bWatchdogReset := TRUE  ;
				iStep		:=	0		;
		END_IF
	
	40:		// Step 40	:	Saw CUT movement
		IF
				bAutoCrossCut
				AND bSafetyOK
				AND	NOT bCrossCutLeftLimit
			THEN
				bAutoCut	:=	TRUE	;
				bWatchdogReset := FALSE ;
		ELSE
				bAutoCut	:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	50		;
		END_IF
		
		IF 		NOT bSafetyOK
			THEN 	
				bAutoCut	:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	0		;
		END_IF
	
	50:		// Step 50	:	Saw UP movement		(* for double pass: only lift slightly, RETURN, then plunge all the way down *)
	ctu_DoublePass.CV;	
		IF
				bAutoCrossCutDoublePass AND bDoublePassCountUp AND NOT bDoublePassQ
			THEN
				bTON_AutoUp	:=	TRUE	;
				bWatchdogReset := FALSE ;
				bAutoUp		:=	NOT TON_bAutoUp.Q	;
				
				IF
					R_TRIG_0.Q THEN
					bWatchdogReset := TRUE ;
					iStep	:=	60	;
				END_IF
				
		ELSIF
				bAutoCrossCut
				AND bSafetyOK
				AND NOT bSawUpLimit
				AND ((bDoublePassQ AND NOT bDoublePassCountUp AND bAutoCrossCutDoublePass) OR (NOT bAutoCrossCutDoublePass))
			THEN
				bAutoUp		:=	TRUE	;
				bWatchdogReset := FALSE ;
		ELSE
				bAutoUp		:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	60		;
		END_IF
		
		IF 		NOT bSafetyOK
		THEN 	
				bAutoUp		:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	0		;
		END_IF
	
	60:		// Step 60	:	Saw RETURN movement (loop back to step 20 if double pass)
		IF
				bAutoCrossCutDoublePass
				AND bDoublePassCountUp
		THEN
				bWatchdogReset := TRUE  ;
				iStep		:=	20		;
		ELSIF	
				bAutoCrossCut
				AND bSafetyOK
				AND NOT bCrossCutCentre
		THEN
				bWatchdogReset := FALSE ;
				bAutoReturn	:=	TRUE	;
		ELSE
				bAutoReturn	:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	0		;
		END_IF
		
		IF 		NOT bSafetyOK
		THEN 	
				bAutoReturn	:=	FALSE	;
				bWatchdogReset := TRUE	;
				iStep		:=	0		;
		END_IF
END_CASE]]></ST>
    </Implementation>
    <Action Name="ACT_08_1_AutoCrossCut" Id="{63a0db5e-5485-4feb-b0e7-b93f232749ba}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"SR"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"SR_WatchdogTriggered"</v>
                          <v n="Type">"SR"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">168L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems">
                            <n />
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeBox">
                            <v n="BoxType">"R_TRIG"</v>
                            <o n="Instance" t="Operand">
                              <v n="Operand">"R_TRIG_7"</v>
                              <v n="Type">"R_TRIG"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">166L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems">
                                <n />
                              </l2>
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeBox">
                              <o>
                                <v n="BoxType">"TON"</v>
                                <o n="Instance" t="Operand">
                                  <v n="Operand">"TON_AutoCrossCutWatchdog"</v>
                                  <v n="Type">"TON"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">105L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" cet="Operand">
                                    <n />
                                    <o>
                                      <v n="Operand">""</v>
                                      <n n="Type" />
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">true</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">107L</v>
                                    </o>
                                  </l2>
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems">
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"SR"</v>
                                    <o n="Instance" t="Operand">
                                      <v n="Operand">"SR_watchdog"</v>
                                      <v n="Type">"SR"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">112L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems">
                                        <n />
                                      </l2>
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems" cet="BoxTreeBox">
                                      <o>
                                        <v n="BoxType">"OR"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">116L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems">
                                            <n />
                                          </l2>
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems" cet="BoxTreeBox">
                                          <o>
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_1"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">148L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeBox">
                                              <o>
                                                <v n="BoxType">"EQ"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">124L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems">
                                                    <n />
                                                  </l2>
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">true</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems" cet="BoxTreeOperand">
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"iStep"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">109L</v>
                                                    </o>
                                                    <v n="Id">108L</v>
                                                  </o>
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"20"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">123L</v>
                                                    </o>
                                                    <v n="Id">122L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" cet="String">
                                                    <v></v>
                                                  </l2>
                                                  <l2 n="Types" cet="String">
                                                    <v>BOOL</v>
                                                  </l2>
                                                </o>
                                                <v n="CallType" t="Operator">Eq</v>
                                                <v n="EN">false</v>
                                                <v n="ENO">false</v>
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">125L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">149L</v>
                                          </o>
                                          <o>
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_2"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">150L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeBox">
                                              <o>
                                                <v n="BoxType">"EQ"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">126L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems">
                                                    <n />
                                                  </l2>
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">false</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems" cet="BoxTreeOperand">
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"iStep"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">119L</v>
                                                    </o>
                                                    <v n="Id">118L</v>
                                                  </o>
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"30"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">129L</v>
                                                    </o>
                                                    <v n="Id">128L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" cet="String">
                                                    <v></v>
                                                  </l2>
                                                  <l2 n="Types" cet="String">
                                                    <v>BOOL</v>
                                                  </l2>
                                                </o>
                                                <v n="CallType" t="Operator">Eq</v>
                                                <v n="EN">false</v>
                                                <v n="ENO">false</v>
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">127L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">151L</v>
                                          </o>
                                          <o>
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_3"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">152L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeBox">
                                              <o>
                                                <v n="BoxType">"EQ"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">136L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems">
                                                    <n />
                                                  </l2>
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">false</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems" cet="BoxTreeOperand">
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"iStep"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">131L</v>
                                                    </o>
                                                    <v n="Id">130L</v>
                                                  </o>
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"40"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">139L</v>
                                                    </o>
                                                    <v n="Id">138L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" cet="String">
                                                    <v></v>
                                                  </l2>
                                                  <l2 n="Types" cet="String">
                                                    <v>BOOL</v>
                                                  </l2>
                                                </o>
                                                <v n="CallType" t="Operator">Eq</v>
                                                <v n="EN">false</v>
                                                <v n="ENO">false</v>
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">137L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">153L</v>
                                          </o>
                                          <o>
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_4"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">154L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeBox">
                                              <o>
                                                <v n="BoxType">"EQ"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">140L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems">
                                                    <n />
                                                  </l2>
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">false</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems" cet="BoxTreeOperand">
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"iStep"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">133L</v>
                                                    </o>
                                                    <v n="Id">132L</v>
                                                  </o>
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"50"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">143L</v>
                                                    </o>
                                                    <v n="Id">142L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" cet="String">
                                                    <v></v>
                                                  </l2>
                                                  <l2 n="Types" cet="String">
                                                    <v>BOOL</v>
                                                  </l2>
                                                </o>
                                                <v n="CallType" t="Operator">Eq</v>
                                                <v n="EN">false</v>
                                                <v n="ENO">false</v>
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">141L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">155L</v>
                                          </o>
                                          <o>
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_5"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">156L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeBox">
                                              <o>
                                                <v n="BoxType">"EQ"</v>
                                                <o n="Instance" t="Operand">
                                                  <n n="Operand" />
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">true</v>
                                                  <v n="Id">144L</v>
                                                </o>
                                                <o n="OutputItems" t="OutputItemList">
                                                  <l2 n="OutputItems">
                                                    <n />
                                                  </l2>
                                                </o>
                                                <o n="Flags" t="Flags">
                                                  <v n="Flags">0</v>
                                                  <v n="Fixed">false</v>
                                                  <v n="Extensible">false</v>
                                                </o>
                                                <n n="InputFlags" />
                                                <l2 n="InputItems" cet="BoxTreeOperand">
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"iStep"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">135L</v>
                                                    </o>
                                                    <v n="Id">134L</v>
                                                  </o>
                                                  <o>
                                                    <o n="Operand" t="Operand">
                                                      <v n="Operand">"60"</v>
                                                      <v n="Type">"INT"</v>
                                                      <v n="Comment">""</v>
                                                      <v n="SymbolComment">""</v>
                                                      <v n="Address">""</v>
                                                      <o n="Flags" t="Flags">
                                                        <v n="Flags">0</v>
                                                        <v n="Fixed">false</v>
                                                        <v n="Extensible">false</v>
                                                      </o>
                                                      <v n="LValue">false</v>
                                                      <v n="Boolean">false</v>
                                                      <v n="IsInstance">false</v>
                                                      <v n="Id">147L</v>
                                                    </o>
                                                    <v n="Id">146L</v>
                                                  </o>
                                                </l2>
                                                <o n="InputParam" t="ParamList">
                                                  <l2 n="Names" />
                                                  <l2 n="Types" />
                                                </o>
                                                <o n="OutputParam" t="ParamList">
                                                  <l2 n="Names" cet="String">
                                                    <v></v>
                                                  </l2>
                                                  <l2 n="Types" cet="String">
                                                    <v>BOOL</v>
                                                  </l2>
                                                </o>
                                                <v n="CallType" t="Operator">Eq</v>
                                                <v n="EN">false</v>
                                                <v n="ENO">false</v>
                                                <n n="STSnippet" />
                                                <v n="ContainsExtensibleInputs">false</v>
                                                <v n="ProvidesSTSnippet">false</v>
                                                <v n="Id">145L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">157L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" cet="String">
                                            <v></v>
                                          </l2>
                                          <l2 n="Types" cet="String">
                                            <v>BOOL</v>
                                          </l2>
                                        </o>
                                        <v n="CallType" t="Operator">Or</v>
                                        <v n="EN">false</v>
                                        <v n="ENO">false</v>
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">117L</v>
                                      </o>
                                      <o>
                                        <v n="BoxType">"OR"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">158L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems">
                                            <n />
                                          </l2>
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <l2 n="InputFlags" cet="Flags">
                                          <o>
                                            <v n="Flags">1</v>
                                            <v n="Fixed">true</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <o>
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <o>
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                        </l2>
                                        <l2 n="InputItems">
                                          <o t="BoxTreeOperand">
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bSafetyOK"</v>
                                              <v n="Type">"BOOL"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">115L</v>
                                            </o>
                                            <v n="Id">114L</v>
                                          </o>
                                          <o t="BoxTreeOperand">
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"IN_FaultReset"</v>
                                              <v n="Type">"BOOL"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">161L</v>
                                            </o>
                                            <v n="Id">160L</v>
                                          </o>
                                          <o t="BoxTreeBox">
                                            <v n="BoxType">"R_TRIG"</v>
                                            <o n="Instance" t="Operand">
                                              <v n="Operand">"R_TRIG_6"</v>
                                              <v n="Type">"R_TRIG"</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">164L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems">
                                                <n />
                                              </l2>
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeOperand">
                                              <o>
                                                <o n="Operand" t="Operand">
                                                  <v n="Operand">"bWatchdogReset"</v>
                                                  <v n="Type">"BOOL"</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">163L</v>
                                                </o>
                                                <v n="Id">162L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>CLK</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" cet="String">
                                                <v>Q</v>
                                              </l2>
                                              <l2 n="Types" cet="String">
                                                <v>BOOL</v>
                                              </l2>
                                            </o>
                                            <v n="CallType" t="Operator">FunctionBlock</v>
                                            <v n="EN">false</v>
                                            <v n="ENO">false</v>
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">165L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" cet="String">
                                            <v></v>
                                          </l2>
                                          <l2 n="Types" cet="String">
                                            <v>BOOL</v>
                                          </l2>
                                        </o>
                                        <v n="CallType" t="Operator">Or</v>
                                        <v n="EN">false</v>
                                        <v n="ENO">false</v>
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">159L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v>SET1</v>
                                        <v>RESET</v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                        <v>BOOL</v>
                                      </l2>
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" cet="String">
                                        <v>Q1</v>
                                      </l2>
                                      <l2 n="Types" cet="String">
                                        <v>BOOL</v>
                                      </l2>
                                    </o>
                                    <v n="CallType" t="Operator">FunctionBlock</v>
                                    <v n="EN">false</v>
                                    <v n="ENO">false</v>
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">113L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"T#3m"</v>
                                      <v n="Type">"TIME"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">111L</v>
                                    </o>
                                    <v n="Id">110L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>IN</v>
                                    <v>PT</v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                    <v>TIME</v>
                                  </l2>
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>Q</v>
                                    <v>ET</v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                    <v>TIME</v>
                                  </l2>
                                </o>
                                <v n="CallType" t="Operator">FunctionBlock</v>
                                <v n="EN">false</v>
                                <v n="ENO">false</v>
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">106L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>CLK</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                              </l2>
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>Q</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                              </l2>
                            </o>
                            <v n="CallType" t="Operator">FunctionBlock</v>
                            <v n="EN">false</v>
                            <v n="ENO">false</v>
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">167L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"IN_FaultReset"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">171L</v>
                            </o>
                            <v n="Id">170L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>SET1</v>
                            <v>RESET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q1</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">169L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">104L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"R_TRIG"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"R_TRIG_0"</v>
                          <v n="Type">"R_TRIG"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">9L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems">
                            <n />
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeBox">
                          <o>
                            <v n="BoxType">"TON"</v>
                            <o n="Instance" t="Operand">
                              <v n="Operand">"TON_bAutoUp"</v>
                              <v n="Type">"TON"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">2L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" cet="Operand">
                                <n />
                                <o>
                                  <v n="Operand">""</v>
                                  <n n="Type" />
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">true</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">4L</v>
                                </o>
                              </l2>
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeOperand">
                              <o>
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"bTON_AutoUp"</v>
                                  <v n="Type">"BOOL"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">6L</v>
                                </o>
                                <v n="Id">5L</v>
                              </o>
                              <o>
                                <o n="Operand" t="Operand">
                                  <v n="Operand">"T#3s"</v>
                                  <v n="Type">"TIME"</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">false</v>
                                  <v n="Id">8L</v>
                                </o>
                                <v n="Id">7L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>IN</v>
                                <v>PT</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                                <v>TIME</v>
                              </l2>
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" cet="String">
                                <v>Q</v>
                                <v>ET</v>
                              </l2>
                              <l2 n="Types" cet="String">
                                <v>BOOL</v>
                                <v>TIME</v>
                              </l2>
                            </o>
                            <v n="CallType" t="Operator">FunctionBlock</v>
                            <v n="EN">false</v>
                            <v n="ENO">false</v>
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">3L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>CLK</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">10L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"bAutoCrossCutErr"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">19L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"TON"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"TON_AutoCrossCutError"</v>
                            <v n="Type">"TON"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">12L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <n n="Type" />
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">14L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bAutoCrossCut"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">16L</v>
                              </o>
                              <v n="Id">15L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"T#10m"</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">18L</v>
                              </o>
                              <v n="Id">17L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>IN</v>
                              <v>PT</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q</v>
                              <v>ET</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">13L</v>
                        </o>
                        <v n="Id">20L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">11L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"bDoublePassQ"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">69L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"SR"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"SR_DoublePass"</v>
                            <v n="Type">"SR"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">22L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeBox">
                            <o>
                              <v n="BoxType">"CTU"</v>
                              <o n="Instance" t="Operand">
                                <v n="Operand">"CTU_DoublePass"</v>
                                <v n="Type">"CTU"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">28L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems" cet="Operand">
                                  <n />
                                  <o>
                                    <v n="Operand">""</v>
                                    <n n="Type" />
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">true</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">30L</v>
                                  </o>
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"AND"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">35L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems">
                                    <o t="BoxTreeOperand">
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"bAutoCrossCutDoublePass"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">38L</v>
                                      </o>
                                      <v n="Id">37L</v>
                                    </o>
                                    <o t="BoxTreeBox">
                                      <v n="BoxType">"EQ"</v>
                                      <o n="Instance" t="Operand">
                                        <n n="Operand" />
                                        <v n="Type">""</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">true</v>
                                        <v n="Id">41L</v>
                                      </o>
                                      <o n="OutputItems" t="OutputItemList">
                                        <l2 n="OutputItems">
                                          <n />
                                        </l2>
                                      </o>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <n n="InputFlags" />
                                      <l2 n="InputItems" cet="BoxTreeOperand">
                                        <o>
                                          <o n="Operand" t="Operand">
                                            <v n="Operand">"iStep"</v>
                                            <v n="Type">"INT"</v>
                                            <v n="Comment">""</v>
                                            <v n="SymbolComment">""</v>
                                            <v n="Address">""</v>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <v n="LValue">false</v>
                                            <v n="Boolean">false</v>
                                            <v n="IsInstance">false</v>
                                            <v n="Id">44L</v>
                                          </o>
                                          <v n="Id">43L</v>
                                        </o>
                                        <o>
                                          <o n="Operand" t="Operand">
                                            <v n="Operand">"30"</v>
                                            <v n="Type">"INT"</v>
                                            <v n="Comment">""</v>
                                            <v n="SymbolComment">""</v>
                                            <v n="Address">""</v>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <v n="LValue">false</v>
                                            <v n="Boolean">false</v>
                                            <v n="IsInstance">false</v>
                                            <v n="Id">46L</v>
                                          </o>
                                          <v n="Id">45L</v>
                                        </o>
                                      </l2>
                                      <o n="InputParam" t="ParamList">
                                        <l2 n="Names" />
                                        <l2 n="Types" />
                                      </o>
                                      <o n="OutputParam" t="ParamList">
                                        <l2 n="Names" cet="String">
                                          <v></v>
                                        </l2>
                                        <l2 n="Types" cet="String">
                                          <v>BOOL</v>
                                        </l2>
                                      </o>
                                      <v n="CallType" t="Operator">Eq</v>
                                      <v n="EN">false</v>
                                      <v n="ENO">false</v>
                                      <n n="STSnippet" />
                                      <v n="ContainsExtensibleInputs">false</v>
                                      <v n="ProvidesSTSnippet">false</v>
                                      <v n="Id">42L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">And</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">36L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"OR"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">47L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <l2 n="InputFlags" cet="Flags">
                                    <o>
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <o>
                                      <v n="Flags">1</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <o>
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                  </l2>
                                  <l2 n="InputItems">
                                    <o t="BoxTreeOperand">
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"ctu_DoublePass.Q"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">50L</v>
                                      </o>
                                      <v n="Id">49L</v>
                                    </o>
                                    <o t="BoxTreeOperand">
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"bSafetyOK"</v>
                                        <v n="Type">"BOOL"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">52L</v>
                                      </o>
                                      <v n="Id">51L</v>
                                    </o>
                                    <o t="BoxTreeBox">
                                      <v n="BoxType">"EQ"</v>
                                      <o n="Instance" t="Operand">
                                        <n n="Operand" />
                                        <v n="Type">""</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">true</v>
                                        <v n="Id">53L</v>
                                      </o>
                                      <o n="OutputItems" t="OutputItemList">
                                        <l2 n="OutputItems">
                                          <n />
                                        </l2>
                                      </o>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <n n="InputFlags" />
                                      <l2 n="InputItems" cet="BoxTreeOperand">
                                        <o>
                                          <o n="Operand" t="Operand">
                                            <v n="Operand">"iStep"</v>
                                            <v n="Type">"INT"</v>
                                            <v n="Comment">""</v>
                                            <v n="SymbolComment">""</v>
                                            <v n="Address">""</v>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <v n="LValue">false</v>
                                            <v n="Boolean">false</v>
                                            <v n="IsInstance">false</v>
                                            <v n="Id">56L</v>
                                          </o>
                                          <v n="Id">55L</v>
                                        </o>
                                        <o>
                                          <o n="Operand" t="Operand">
                                            <v n="Operand">"0"</v>
                                            <v n="Type">"INT"</v>
                                            <v n="Comment">""</v>
                                            <v n="SymbolComment">""</v>
                                            <v n="Address">""</v>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <v n="LValue">false</v>
                                            <v n="Boolean">false</v>
                                            <v n="IsInstance">false</v>
                                            <v n="Id">58L</v>
                                          </o>
                                          <v n="Id">57L</v>
                                        </o>
                                      </l2>
                                      <o n="InputParam" t="ParamList">
                                        <l2 n="Names" />
                                        <l2 n="Types" />
                                      </o>
                                      <o n="OutputParam" t="ParamList">
                                        <l2 n="Names" cet="String">
                                          <v></v>
                                        </l2>
                                        <l2 n="Types" cet="String">
                                          <v>BOOL</v>
                                        </l2>
                                      </o>
                                      <v n="CallType" t="Operator">Eq</v>
                                      <v n="EN">false</v>
                                      <v n="ENO">false</v>
                                      <n n="STSnippet" />
                                      <v n="ContainsExtensibleInputs">false</v>
                                      <v n="ProvidesSTSnippet">false</v>
                                      <v n="Id">54L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Or</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">48L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"2"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">34L</v>
                                  </o>
                                  <v n="Id">33L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>CU</v>
                                  <v>RESET</v>
                                  <v>PV</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>BOOL</v>
                                  <v>WORD</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>Q</v>
                                  <v>CV</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>WORD</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">FunctionBlock</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">29L</v>
                            </o>
                            <o>
                              <v n="BoxType">"OR"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">59L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <l2 n="InputFlags" cet="Flags">
                                <o>
                                  <v n="Flags">1</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <o>
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                              </l2>
                              <l2 n="InputItems">
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"bSafetyOK"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">62L</v>
                                  </o>
                                  <v n="Id">61L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"EQ"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">63L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"iStep"</v>
                                        <v n="Type">"INT"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">66L</v>
                                      </o>
                                      <v n="Id">65L</v>
                                    </o>
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"0"</v>
                                        <v n="Type">"INT"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">""</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">68L</v>
                                      </o>
                                      <v n="Id">67L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>BOOL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Eq</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">64L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v></v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Or</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">60L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>SET1</v>
                              <v>RESET</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q1</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">23L</v>
                        </o>
                        <v n="Id">70L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">21L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"bAutoCrossCutEnabled"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">85L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"fb_Blinker"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"FB_Blinker_AutoCrossCut"</v>
                            <v n="Type">"fb_Blinker"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">83L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bAutoCrossCut"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">80L</v>
                              </o>
                              <v n="Id">79L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"T#0.5s"</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">82L</v>
                              </o>
                              <v n="Id">81L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>IN</v>
                              <v>blink_time</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>OUT</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">84L</v>
                        </o>
                        <v n="Id">86L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">76L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"bAutoCrossCutInProgress"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">74L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"bAutoCrossCut"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">73L</v>
                          </o>
                          <v n="Id">72L</v>
                        </o>
                        <v n="Id">75L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">71L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"bAutoCrossCutReady"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">96L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"AND"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">88L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <l2 n="InputFlags" cet="Flags">
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <o>
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                          </l2>
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bSawUpLimit"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">91L</v>
                              </o>
                              <v n="Id">90L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"OUT_bSawOn"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">93L</v>
                              </o>
                              <v n="Id">92L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bTurret045Range"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">95L</v>
                              </o>
                              <v n="Id">94L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bCarriageCentreRef"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">99L</v>
                              </o>
                              <v n="Id">98L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bMachineHoming"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">101L</v>
                              </o>
                              <v n="Id">100L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"bCrossCutPosition"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">103L</v>
                              </o>
                              <v n="Id">102L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" />
                            <l2 n="Types" />
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v></v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">And</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">89L</v>
                        </o>
                        <v n="Id">97L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">87L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="PRG_08_AutoCrossCut">
      <LineId Id="6" Count="1" />
      <LineId Id="215" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="198" Count="0" />
      <LineId Id="196" Count="0" />
      <LineId Id="199" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="197" Count="0" />
      <LineId Id="10" Count="8" />
      <LineId Id="166" Count="0" />
      <LineId Id="20" Count="7" />
      <LineId Id="213" Count="0" />
      <LineId Id="28" Count="6" />
      <LineId Id="181" Count="0" />
      <LineId Id="35" Count="2" />
      <LineId Id="211" Count="0" />
      <LineId Id="38" Count="2" />
      <LineId Id="212" Count="0" />
      <LineId Id="41" Count="9" />
      <LineId Id="209" Count="0" />
      <LineId Id="51" Count="2" />
      <LineId Id="210" Count="0" />
      <LineId Id="54" Count="5" />
      <LineId Id="214" Count="0" />
      <LineId Id="60" Count="11" />
      <LineId Id="216" Count="0" />
      <LineId Id="72" Count="3" />
      <LineId Id="217" Count="0" />
      <LineId Id="76" Count="6" />
      <LineId Id="218" Count="0" />
      <LineId Id="83" Count="9" />
      <LineId Id="219" Count="0" />
      <LineId Id="93" Count="1" />
      <LineId Id="220" Count="0" />
      <LineId Id="95" Count="5" />
      <LineId Id="221" Count="0" />
      <LineId Id="101" Count="8" />
      <LineId Id="222" Count="0" />
      <LineId Id="110" Count="3" />
      <LineId Id="223" Count="0" />
      <LineId Id="114" Count="9" />
      <LineId Id="224" Count="0" />
      <LineId Id="124" Count="1" />
      <LineId Id="225" Count="0" />
      <LineId Id="126" Count="5" />
      <LineId Id="226" Count="0" />
      <LineId Id="132" Count="7" />
      <LineId Id="227" Count="0" />
      <LineId Id="140" Count="5" />
      <LineId Id="228" Count="0" />
      <LineId Id="146" Count="2" />
      <LineId Id="229" Count="0" />
      <LineId Id="149" Count="2" />
      <LineId Id="231" Count="4" />
      <LineId Id="230" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>