<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_09_HomePosition" Id="{69d55c69-25db-4051-96ce-df52250d7317}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_09_HomePosition
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_09_HomePosition">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>